#!/bin/sh

stamp=$(update-notifier --stamp)

if [ -r "$stamp" ] && [ -s "$stamp" ]; then
    echo
    cat "$stamp"

    if ! find "$stamp" -newermt 'now-7 days' 2> /dev/null | grep -q -m 1 '.'; then
        echo ""
        echo "The list of available updates is more than a week old."
        echo "To check for new updates run: brew update"
    fi
fi