#!/bin/sh
#
#    90-updates-available - print information about package updates
#    Copyright (c) 2024 Ian McLinden
#
#    Based on files included with Canonical Ltd. update-motd
#    Copyright (C) 2009-2010 Canonical Ltd.
#
#    Authors: Dustin Kirkland <kirkland@canonical.com>,
#             Brian Murray <brian@canonical.com>
#
#    This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program. If not, see <https://www.gnu.org/licenses/>.
#
stamp=$(update-notifier --stamp)

if [ -r "$stamp" ] && [ -s "$stamp" ]; then
    echo
    cat "$stamp"

    if ! find "$stamp" -newermt 'now-7 days' 2> /dev/null | grep -q -m 1 '.'; then
        echo ""
        echo "The list of available updates is more than a week old."
        echo "To check for new updates run: brew update"
    fi
fi