#!/bin/bash
#
#    99-last-login - print last login information
#    Copyright (c) 2024 Ian McLinden
#
#    This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program. If not, see <https://www.gnu.org/licenses/>.
#
PATTERN='^([^ ]+)[ ]{2,}([^ ]+)[ ]{2,}([^ ]+)?[ ]{2,}(.*)[ ]{2,}(.*)$'
if [[ "$(last -2 "$(whoami)"| tail -1)" =~ $PATTERN ]]; then

    DATE="${BASH_REMATCH[4]}"
    SRC="${BASH_REMATCH[3]:-${BASH_REMATCH[2]}}"

    echo
    echo "Last login: ${DATE} from ${SRC}"
fi