#!/bin/bash

PATTERN='^([^ ]+)[ ]{2,}([^ ]+)[ ]{2,}([^ ]+)?[ ]{2,}(.*)[ ]{2,}(.*)$'
if [[ "$(last -2 "$(whoami)"| tail -1)" =~ $PATTERN ]]; then

    DATE="${BASH_REMATCH[4]}"
    SRC="${BASH_REMATCH[3]:-${BASH_REMATCH[2]}}"

    echo
    echo "Last login: ${DATE} from ${SRC}"
fi